# Site settings
title: Balı
description: Maker Space
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Balı
user_description: 

# twitter_username: lorem_ipsum
instagram_username: abdbali
# facebook_username: lorem_ipsum
linkedin_username: abdbali
github_username:  abdbali
#medium_username: abdbali
# medium_url: https://medium.com/@abdbali
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

