# Site settings
title: BalÄ±
description: Maker Space
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: BalÄ±
user_description: <a href="https://github.com/abdbali/ttwsp" target="https://github.com/abdbali/ttwsp">ğŸ‹ TWO TREES BLUER SAPPHÄ°RE PLUS V1.1 WÄ°-FÄ° DESTEÄÄ°</a>
# twitter_username: lorem_ipsum
instagram_username: abdbali
# facebook_username: lorem_ipsum
linkedin_username: abdbali
github_username:  abdbali
#medium_username: abdbali
# medium_url: https://medium.com/@abdbali
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

